In [1]:
import numpy as np
import torch
import torch.nn.functional

In [3]:
from ActivationFunctions import sigmoid,sigmoid_derivative
from LossFunctions import binary_cross_entropy,binary_cross_entropy_derivative,binary_cross_entropy_sigmoid,binary_cross_entropy_sigmoid_derivative

In [4]:
a=np.array([[1.5],[2.5],[3.5]])
aTensor=torch.tensor(a)
aTensor.requires_grad_()
sigmoidTensor=torch.nn.functional.sigmoid(aTensor)
sigmoidTensor.requires_grad_()
sigmoidTensor.retain_grad()
label=np.array([[1],[0],[1]])
labelTensor=torch.tensor(label).double()
labelTensor.requires_grad=False

C:\Users\Silas\Programs\Academic\anaconda3\envs\experiments\lib\site-packages\torch\nn\functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [5]:
print(sigmoid(a))
print(sigmoidTensor.detach().numpy())
print(sigmoid_derivative(a))

[[0.81757448]
 [0.92414182]
 [0.97068777]]
[[0.81757448]
 [0.92414182]
 [0.97068777]]
[[0.08256773]]


In [8]:
print(binary_cross_entropy(sigmoid(a),label,"mean"))
print(binary_cross_entropy_sigmoid(a,label,"mean"))

[[0.93668448]]
[[0.93668448]]


In [9]:
loss=torch.nn.functional.binary_cross_entropy(sigmoidTensor,labelTensor,reduction="mean")
print(loss.detach().numpy())

0.936684476849308


In [10]:
loss.backward()

In [11]:
print(aTensor.grad.numpy())
print(sigmoidTensor.grad.numpy())

[[-0.06080851]
 [ 0.30804727]
 [-0.00977074]]
[[-0.40771005]
 [ 4.39416465]
 [-0.34339913]]


In [12]:
print(binary_cross_entropy_sigmoid_derivative(a,label,"mean"))
print(binary_cross_entropy_derivative(sigmoid(a),label,"mean"))

[[-0.06080851]
 [ 0.30804727]
 [-0.00977074]]
[[-0.40771005]
 [ 4.39416465]
 [-0.34339913]]


In [10]:
(sigmoid(a)-label)/(sigmoid(a)*(1-sigmoid(a)))

array([[-1.22313016],
       [13.18249396],
       [-1.03019738]])